import type { Metadata } from 'next';
import Link from 'next/link';
import FinalCTA from '@/components/FinalCTA';
import Breadcrumbs from '@/components/Breadcrumbs';

export const metadata: Metadata = {
  title: 'Molasses Supplier Haryana | Bulk Sugarcane Sourcing | Saarthi Organics',
  description: 'High-Brix sugarcane molasses supplier in Haryana. Coordinated from Karnal for distilleries, feed mills, and yeast processors across Yamunanagar, Panipat, and Sonipat.',
  alternates: {
    canonical: 'https://www.saarthiorganics.com/molasses-supplier-haryana',
  },
};

export default function HaryanaSupplierPage() {
  const localSchema = {
    "@context": "https://schema.org",
    "@type": "LocalBusiness",
    "name": "Saarthi Organics (Haryana Sourcing Hub)",
    "image": "https://www.saarthiorganics.com/logo_heritage.jpg",
    "telephone": ["+91-7055552535", "+91-9927029029", "+91-9837022300"],
    "email": "contact@saarthiorganics.com",
    "address": {
      "@type": "PostalAddress",
      "streetAddress": "Farm House, Liberty Chowk",
      "addressLocality": "Karnal",
      "addressRegion": "Haryana",
      "postalCode": "132001",
      "addressCountry": "IN"
    },
    "url": "https://www.saarthiorganics.com/molasses-supplier-haryana"
  };

  const regionalFaqs = [
    {
      q: "How does Saarthi Organics coordinate Haryana sugarcane molasses dispatches?",
      a: "Our core administrative sourcing desk is based directly in Karnal, Haryana. We maintain standing allocations with sugar mills across Yamunanagar, Panipat, Shahabad, and Sonipat. Once transit passes are generated by the Haryana Excise department, tankers are loaded under strict QA inspections and dispatched directly from the mill sites to your industrial plant."
    },
    {
      q: "What is the typical Brix and sugar specification of Haryana sugarcane molasses?",
      a: "Haryana molasses typically registers a Brix density between 81% and 84%. The Total Reducing Sugars (TRS) range from 44% to 48%, making it an excellent fermentable feedstock. We provide batch-wise lab reports indicating purity, ash content, and density to guarantee processing stability."
    },
    {
      q: "Are your liquid tanker shipments GST and Excise compliant?",
      a: "Absolutely. All sugarcane molasses dispatches in Haryana are strictly registered under the State Excise department's online portal. We issue digital e-way bills, GST-compliant tax invoices, and official mill weighment slips. Procurement heads can easily file for Input Tax Credit (ITC) without compliance complications."
    },
    {
      q: "Do you supply small industrial orders or samples in Haryana?",
      a: "For industrial validations, we dispatch pre-shipment sample kits (2kg to 5kg) to plant quality control labs. For commercial orders, our minimum order quantity (MOQ) is one full road tanker, carrying approximately 20 to 25 Metric Tons of liquid molasses."
    }
  ];

  return (
    <main style={{ marginTop: '72px', background: 'var(--bg-primary)', color: 'var(--text-primary)' }}>
      <Breadcrumbs items={[{ name: 'Haryana Supplier', href: '/molasses-supplier-haryana' }]} />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(localSchema) }}
      />

      <div className="subpage-hero">
        <div className="subpage-hero-bg" style={{ backgroundImage: "url('/hero_logistics.png')" }} />
        <div className="subpage-hero-overlay" />
        <div className="subpage-hero-container">
          <span className="section-label">Haryana Sourcing & Distribution Hub</span>
          <h1 className="subpage-hero-title">Bulk Sugarcane Molasses Supplier in Haryana</h1>
          <p className="subpage-hero-desc">
            Premium industrial-grade sugarcane molasses with guaranteed Brix density. Handled directly from our Karnal operations desk with full excise compliance and nationwide shipping.
          </p>
        </div>
      </div>

      <section style={{ padding: '60px 24px' }}>
        <div style={{ maxWidth: '1280px', margin: '0 auto', display: 'flex', gap: '60px', alignItems: 'flex-start', flexWrap: 'wrap' }}>
          
          {/* Left Column: Extensive Content */}
          <div style={{ flex: 1.1, minWidth: '300px' }}>
            <h2 className="section-title" style={{ textAlign: 'left', marginBottom: '24px' }}>
              Reliable Sugarcane Molasses Distribution Across Haryana
            </h2>
            
            <p className="section-desc" style={{ marginBottom: '20px', textAlign: 'left', lineHeight: '1.6' }}>
              Haryana is a major agricultural corridor in Northern India, producing substantial sugarcane volumes through cooperative and private sugar mills. Saarthi Organics leverages its central sourcing desk in Karnal to secure direct allocations from premier mill zones in <strong>Yamunanagar, Panipat, Shahabad, Rohtak, and Sonipat</strong>. By coordinating procurement directly at the mill gates, we eliminate intermediate traders and ensure that our clients receive unadulterated, high-density sugarcane molasses at competitive prices.
            </p>
            
            <p className="section-desc" style={{ marginBottom: '20px', textAlign: 'left', lineHeight: '1.6' }}>
              Our commercial molasses sourcing operations are engineered for consistency. We understand that industrial fermenters and production lines cannot tolerate fluctuations in quality. Hence, we strictly source material that exhibits an optimal balance of total reducing sugars and stable moisture content. This focus makes our molasses highly sought-after by biotechnology plants, feed manufacturers, and industrial ethanol processors.
            </p>

            <h3 style={{ fontSize: '1.4rem', margin: '36px 0 16px 0', color: 'var(--accent-gold)' }}>Key Haryana Industries We Serve</h3>
            <p className="section-desc" style={{ marginBottom: '20px', textAlign: 'left', lineHeight: '1.6' }}>
              Our customer base in Haryana is highly diverse, ranging from heavy industrial processing to large-scale agriculture:
            </p>
            <ul style={{ paddingLeft: '20px', marginBottom: '24px', color: 'var(--text-secondary)', lineHeight: '1.8' }}>
              <li><strong>Cattle Feed Manufacturing:</strong> Haryana has a massive livestock sector. We supply feed mills in Karnal, Kurukshetra, and Jind with high-sugar molasses that acts as a natural binder, pellet dust reducer, and energy-dense nutritional additive.</li>
              <li><strong>Bio-Ethanol & Distilleries:</strong> With the national mandate for fuel blending, distilleries in Yamunanagar and Ambala rely on our high Total Reducing Sugars (TRS) molasses to maximize alcohol yield per metric ton.</li>
              <li><strong>Yeast & Fermentation Plants:</strong> Our low-ash, clean sugarcane molasses serves as a nutrient-rich growth medium for biological yeast and enzymes production facilities.</li>
            </ul>

            <h3 style={{ fontSize: '1.4rem', margin: '36px 0 16px 0', color: 'var(--accent-gold)' }}>Excise Compliance & Fleet Logistics</h3>
            <p className="section-desc" style={{ marginBottom: '20px', textAlign: 'left', lineHeight: '1.6' }}>
              Moving liquid molasses within Haryana requires navigating strict state excise mandates. Saarthi Organics manages the entire legal pathway, from obtaining the initial mill dispatch permit to generating online excise passes and e-way bills.
            </p>
            <p className="section-desc" style={{ marginBottom: '20px', textAlign: 'left', lineHeight: '1.6' }}>
              We operate an in-house fleet of specialized MS and SS liquid road tankers. Each vehicle is equipped with GPS tracking and is driven by experienced operators who specialize in transporting heavy, viscous fluids. This ensures that cargo arrives on-time, untampered, and ready for immediate storage tank unloading.
            </p>

            <div className="symmetrical-grid-two-col" style={{ marginTop: '30px', marginBottom: '36px' }}>
              <div className="symmetrical-detail-box" style={{ margin: 0 }}>
                <strong style={{ color: 'var(--accent-amber)' }}>Direct Mill Operations</strong>
                <p style={{ fontSize: '0.9rem', lineHeight: '1.4' }}>Standing allocations at major sugar mills ensure steady inventory supply even during peak seasonal demand spikes.</p>
              </div>
              <div className="symmetrical-detail-box" style={{ margin: 0 }}>
                <strong style={{ color: 'var(--accent-amber)' }}>Rigorous Compliance</strong>
                <p style={{ fontSize: '0.9rem', lineHeight: '1.4' }}>GST invoicing, weighment certification, and excise permit processing managed in real-time by our compliance staff.</p>
              </div>
            </div>
          </div>

          {/* Right Column: Sourcing Desk & Specifications */}
          <div style={{ flex: 0.9, minWidth: '300px' }}>
            <div className="quote-contact-card" style={{ background: 'var(--bg-secondary)', border: '1px solid var(--border-color)', borderRadius: '8px', padding: '30px', marginBottom: '30px' }}>
              <h3 style={{ fontSize: '1.3rem', color: 'var(--text-primary)', marginBottom: '12px', fontFamily: "'Cinzel', serif" }}>Haryana Sourcing Desk</h3>
              <p style={{ fontSize: '0.92rem', color: 'var(--text-secondary)', lineHeight: '1.5', marginBottom: '20px' }}>
                Connect directly with our procurement office in Karnal. Request specification sheets, sample kits, and customized transport logistics rates.
              </p>
              
              <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
                <Link href="/contact?region=haryana&subject=Haryana Bulk Sourcing Inquiry" className="btn-primary" style={{ textAlign: 'center', textDecoration: 'none' }}>
                  Request Tanker Quote
                </Link>
                <a href="tel:+917055552535" className="btn-secondary" style={{ textAlign: 'center', textDecoration: 'none' }}>
                  Call +91-7055552535
                </a>
                <a href="tel:+919927029029" className="btn-secondary" style={{ textAlign: 'center', textDecoration: 'none', background: 'transparent', border: '1px solid var(--border-light)' }}>
                  Call +91-9927029029
                </a>
                <a href="tel:+919837022300" className="btn-secondary" style={{ textAlign: 'center', textDecoration: 'none', background: 'transparent', border: '1px solid var(--border-light)' }}>
                  Call +91-9837022300
                </a>
              </div>
            </div>

            <div style={{ background: 'var(--bg-secondary)', border: '1px solid var(--border-color)', borderRadius: '8px', padding: '30px' }}>
              <h3 style={{ fontSize: '1.1rem', color: 'var(--text-primary)', marginBottom: '16px', textTransform: 'uppercase', letterSpacing: '0.5px' }}>Standard Sourcing Spec</h3>
              <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.88rem' }}>
                <tbody>
                  <tr style={{ borderBottom: '1px solid var(--border-light)' }}>
                    <td style={{ padding: '8px 0', color: 'var(--text-secondary)' }}>Brix Density</td>
                    <td style={{ padding: '8px 0', textAlign: 'right', fontWeight: 'bold' }}>82.0% - 84.0%</td>
                  </tr>
                  <tr style={{ borderBottom: '1px solid var(--border-light)' }}>
                    <td style={{ padding: '8px 0', color: 'var(--text-secondary)' }}>Total Reducing Sugar</td>
                    <td style={{ padding: '8px 0', textAlign: 'right', fontWeight: 'bold' }}>44.0% - 48.0%</td>
                  </tr>
                  <tr style={{ borderBottom: '1px solid var(--border-light)' }}>
                    <td style={{ padding: '8px 0', color: 'var(--text-secondary)' }}>Moisture Content</td>
                    <td style={{ padding: '8px 0', textAlign: 'right', fontWeight: 'bold' }}>16.0% - 18.0%</td>
                  </tr>
                  <tr>
                    <td style={{ padding: '8px 0', color: 'var(--text-secondary)' }}>Standard MOQ</td>
                    <td style={{ padding: '8px 0', textAlign: 'right', fontWeight: 'bold' }}>20 - 25 MT (Tanker)</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>

        </div>
      </section>

      {/* Local FAQs Section */}
      <section style={{ padding: '60px 24px', background: 'rgba(255,255,255,0.01)', borderTop: '1px solid var(--border-color)' }}>
        <div style={{ maxWidth: '800px', margin: '0 auto' }}>
          <div style={{ textAlign: 'center', marginBottom: '40px' }}>
            <span className="section-label">Haryana Support FAQ</span>
            <h2 className="section-title">Regional Logistics & Specifications FAQ</h2>
          </div>
          <div className="faq-list">
            {regionalFaqs.map((faq, index) => (
              <details key={index} className="faq-card" style={{ marginBottom: '16px', border: '1px solid var(--border-color)', borderRadius: '6px', background: 'var(--bg-surface)' }}>
                <summary className="faq-question" style={{
                  padding: '20px',
                  fontWeight: '700',
                  fontSize: '1rem',
                  cursor: 'pointer',
                  display: 'flex',
                  justifyContent: 'space-between',
                  alignItems: 'center',
                  background: 'var(--bg-secondary)',
                  color: 'var(--text-primary)',
                  listStyle: 'none'
                }}>
                  <span>{faq.q}</span>
                  <span style={{ color: 'var(--accent-gold)' }}>▼</span>
                </summary>
                <div style={{ padding: '20px', borderTop: '1px solid var(--border-color)', color: 'var(--text-secondary)', background: 'var(--bg-surface)' }}>
                  <p style={{ margin: 0, fontSize: '0.92rem', lineHeight: '1.6' }}>{faq.a}</p>
                </div>
              </details>
            ))}
          </div>
        </div>
      </section>

      <div className="heritage-divider">
        <span className="heritage-divider-motif">✦</span>
      </div>

      <FinalCTA />
    </main>
  );
}

